app/app/urls.py
'''
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

'''
from django.conf.urls import handler400, handler403, handler404, handler500, include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path

import credits.views
import dashboard.embed
import dashboard.helpers
import dashboard.ios
import dashboard.views
import linkshortener.views
import marketing.views
import retail.emails
import retail.views
import tdi.views
from dashboard.router import router

from .sitemaps import sitemaps

urlpatterns = [
    # api views
    url(r'^api/v0.1/profile/(.*)?/keywords', dashboard.views.profile_keywords, name='profile_keywords'),
    url(r'^api/v0.1/funding/save/?', dashboard.ios.save, name='save'),
    url(r'^api/v0.1/', include(router.urls)),
    url(r'^actions/api/v0.1/', include(router.urls)), # same as active, but not cached in cluodfront

    # dashboard views

    # Dummy External Bounties index
    # url(r'^external_bounties/?', dashboard.views.external_bounties, name='external_bounties'),
    # url(r'^external_bounty/?', dashboard.views.external_bounties_show, name="external_bounties_show"),

    url(r'^dashboard/?', dashboard.views.dashboard, name='dashboard'),
    url(r'^explorer/?', dashboard.views.dashboard, name='explorer'),
    url(r'^bounty/new/?', dashboard.views.new_bounty, name='new_bounty'),
    url(r'^funding/new/?', dashboard.views.new_bounty, name='new_funding'),
    url(r'^bounty/fulfill/?', dashboard.views.fulfill_bounty, name='fulfill_bounty'),
    url(r'^funding/fulfill/?', dashboard.views.fulfill_bounty, name='fulfill_funding'),
    url(r'^bounty/process/?', dashboard.views.process_bounty, name='process_bounty'),
    url(r'^funding/process/?', dashboard.views.process_bounty, name='process_funding'),
    url(r'^bounty/details/?', dashboard.views.bounty_details, name='bounty_details'),
    url(r'^funding/details/?', dashboard.views.bounty_details, name='funding_details'),
    url(r'^funding/kill/?', dashboard.views.kill_bounty, name='kill_bounty'),
    url(r'^tip/receive/?', dashboard.views.receive_tip, name='receive_tip'),
    url(r'^tip/send/2/?', dashboard.views.send_tip_2, name='send_tip_2'),
    url(r'^tip/send/?', dashboard.views.send_tip, name='send_tip'),
    url(r'^send/?', dashboard.views.send_tip, name='tip'),
    url(r'^tip/?', dashboard.views.send_tip, name='tip'),
    url(r'^legal/?', dashboard.views.terms, name='legal'),
    url(r'^terms/?', dashboard.views.terms, name='_terms'),
    url(r'^legal/terms/?', dashboard.views.terms, name='terms'),
    url(r'^legal/privacy/?', dashboard.views.privacy, name='privacy'),
    url(r'^legal/cookie/?', dashboard.views.cookie, name='cookie'),
    url(r'^legal/prirp/?', dashboard.views.prirp, name='prirp'),
    url(r'^legal/apitos/?', dashboard.views.apitos, name='apitos'),
    url(r'^funding/embed/?', dashboard.embed.embed, name='embed'),
    url(r'^funding/avatar/?', dashboard.embed.avatar, name='avatar'),
    url(r'^stats/(.*)/?', dashboard.embed.stat, name='stat'),
    url(r'^profile/(.*)?', dashboard.views.profile, name='profile'),
    url(r'^toolbox/?', dashboard.views.toolbox, name='toolbox'),
    url(r'^tools/?', dashboard.views.toolbox, name='tools'),
    url(r'^gas/?', dashboard.views.gas, name='gas'),
    url(r'^coin/redeem/(.*)/?', dashboard.views.redeem_coin, name='redeem'),

    # sync methods
    url(r'^sync/web3', dashboard.views.sync_web3, name='sync_web3'),
    url(r'^sync/get_issue_title?', dashboard.helpers.title, name='helpers_title'),
    url(r'^sync/get_issue_description?', dashboard.helpers.description, name='helpers_description'),
    url(r'^sync/get_amount?', dashboard.helpers.amount, name='helpers_amount'),
    url(r'^sync/get_issue_keywords?', dashboard.helpers.keywords, name='helpers_keywords'),
    url(r'^sync/search_save?', dashboard.views.save_search, name='save_search'),
    # brochureware views
    url(r'^about/?', retail.views.about, name='about'),
    url(r'^mission/?', retail.views.mission, name='mission'),
    url(r'^get/?', retail.views.get_gitcoin, name='get_gitcoin'),
    url(r'^$', retail.views.index, name='index'),
    url(r'^help/dev/?', retail.views.help_dev, name='help_dev'),
    url(r'^help/repo/?', retail.views.help_repo, name='help_repo'),
    url(r'^help/faq?', retail.views.help_faq, name='help_faq'),
    url(r'^help/portal?', retail.views.portal, name='portal'),
    url(r'^help/pilot?', retail.views.help_pilot, name='help_pilot'),
    url(r'^help/?', retail.views.help, name='help'),
    url(r'^onboard/?', retail.views.onboard, name='onboard'),
    url(r'^extension/chrome?', retail.views.browser_extension_chrome, name='browser_extension_chrome'),
    url(r'^extension/firefox?', retail.views.browser_extension_firefox, name='browser_extension_firefox'),
    url(r'^extension/?', retail.views.browser_extension_chrome, name='browser_extension'),
    # basic redirect retail views
    url(r'^press/?', retail.views.presskit, name='press'),
    url(r'^presskit/?', retail.views.presskit, name='presskit'),
    url(r'^community/?', retail.views.community, name='community'),
    url(r'^slack/?', retail.views.slack, name='slack'),
    url(r'^iosfeedback/?', retail.views.iosfeedback, name='iosfeedback'),
    url(r'^ios/?', retail.views.ios, name='ios'),
    url(r'^itunes/?', retail.views.itunes, name='itunes'),
    url(r'^ethdenverafterparty/?', retail.views.ethdenverafterparty, name='ethdenverafterparty'),
    url(r'^ethdenver/?', retail.views.ethdenver, name='ethdenver'),
    url(r'^denver/?', retail.views.ethdenver, name='denver'),
    url(r'^casestudy/?', retail.views.casestudy, name='casestudy'),
    url(r'^casestudies/?', retail.views.casestudy, name='casestudies'),
    url(r'^schwag/?', retail.views.schwag, name='schwag'),
    url(r'^btctalk/?', retail.views.btctalk, name='btctalk'),
    url(r'^reddit/?', retail.views.reddit, name='reddit'),
    url(r'^feedback/?', retail.views.feedback, name='feedback'),
    url(r'^twitter/?', retail.views.twitter, name='twitter'),
    url(r'^gitter/?', retail.views.gitter, name='gitter'),
    url(r'^refer/?', retail.views.refer, name='refer'),
    url(r'^fb/?', retail.views.fb, name='fb'),
    url(r'^medium/?', retail.views.medium, name='medium'),
    url(r'^github/?', retail.views.github, name='github'),
    url(r'^youtube/?', retail.views.youtube, name='youtube'),

    # link shortener
    url(r'^l/(.*)$/?', linkshortener.views.linkredirect, name='redirect'),
    url(r'^credit/(.*)$/?', credits.views.credits, name='credit'),

    # token distribution event
    url(r'^whitepaper/accesscode?', tdi.views.whitepaper_access, name='whitepaper_access'),
    url(r'^whitepaper/?', tdi.views.whitepaper_new, name='whitepaper'),
    # admin views
    url(r'^_administration/?', admin.site.urls, name='admin'),
    url(r'^_administration/email/new_bounty$', retail.emails.new_bounty, name='new_bounty'),
    url(r'^_administration/email/roundup$', retail.emails.roundup, name='roundup'),
    url(r'^_administration/email/new_tip$', retail.emails.new_tip, name='new_tip'),
    url(r'^_administration/email/new_match$', retail.emails.new_match, name='new_match'),
    url(r'^_administration/email/new_work_submission$', retail.emails.new_work_submission, name='new_work_submission'),
    url(r'^_administration/email/new_bounty_rejection$', retail.emails.new_bounty_rejection, name='new_bounty_rejection'),
    url(r'^_administration/email/new_bounty_acceptance$', retail.emails.new_bounty_acceptance, name='new_bounty_acceptance'),
    url(r'^_administration/email/bounty_expire_warning$', retail.emails.bounty_expire_warning, name='bounty_expire_warning'),
    url(r'^_administration/email/start_work_expire_warning$', retail.emails.start_work_expire_warning, name='start_work_expire_warning'),
    url(r'^_administration/email/start_work_expired$', retail.emails.start_work_expired, name='start_work_expired'),
    url(r'^_administration/process_accesscode_request/(.*)$', tdi.views.process_accesscode_request, name='process_accesscode_request'),
    url(r'^_administration/email/new_tip/resend$', retail.emails.resend_new_tip, name='resend_new_tip'),
    # marketing views
    url(r'^email/settings/(.*)', marketing.views.email_settings, name='email_settings'),
    url(r'^leaderboard/(.*)', marketing.views.leaderboard, name='leaderboard'),
    url(r'^leaderboard', marketing.views._leaderboard, name='_leaderboard'),
    url(r'^_administration/stats$', marketing.views.stats, name='stats'),
    # for robots
    url(r'^robots.txt/?', retail.views.robotstxt, name='robotstxt'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # Github Integration
    path('_github/', include('github.urls', namespace='github')),
    # Interests
    path('actions/bounty/<int:bounty_id>/interest/new/', dashboard.views.new_interest, name='express-interest'),
    path('actions/bounty/<int:bounty_id>/interest/remove/', dashboard.views.remove_interest, name='remove-interest'),
    path('actions/bounty/<int:bounty_id>/interest/', dashboard.views.interested_profiles, name='interested-profiles'),
    # Legacy Support
    path('legacy/', include('legacy.urls', namespace='legacy')),
]

handler403 = 'retail.views.handler403'
handler404 = 'retail.views.handler404'

app/github/urls.py
# -*- coding: utf-8 -*-
"""Handle github URLs.

Copyright (C) 2018 Gitcoin Core

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

"""

from django.urls import path

from .views import github_authentication, github_callback, github_logout

app_name = 'github'
urlpatterns = [
    path('callback/', github_callback, name='github_callback'),
    path('auth/', github_authentication, name='github_auth'),
    path('logout/', github_logout, name='github_logout'),
]

app/dashboard/templates/shared/bounty_def.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}
{% load static %}
                <div class="bounty_def">
                    <div class="row mt-4  mb-4 align-items-center ml-4" >
                        <div class="col-1">
                            <img src="{% static "v2/images/icons/message_txt.png" %}" />
                        </div>
                        <div class="col-7">
                            <h5>Be the first to know about new funded issues.</h5>
                            {% include 'shared/mailchimp.html' %}

                        </div>
                    </div>
                </div>

app/dashboard/templates/shared/bounty_nav.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}

                            <div class="w-100" style="text-align: center;">
                                <ol class="bounty_nav">
                                    <li class="{% if active_item == 1 %}active{%endif%} submit" >
                                        1.
                                        {% if past_tense %}
                                            Open
                                        {%else%}
                                            Create Work
                                        {%endif%}
                                    </li>
                                    <li class="{% if active_item == 2 %}active{%endif%} fulfill">
                                        2.
                                        {% if past_tense %}
                                            Work Started
                                        {%else%}
                                            Start Work
                                        {%endif%}
                                    </li>
                                    <li class="{% if active_item == 3 %}active{%endif%} fulfill">
                                        3.
                                        {% if past_tense %}
                                            Work Submitted
                                        {%else%}
                                            Submit Work
                                        {%endif%}
                                    </li>
                                    <li class="{% if active_item == 4 %}active{%endif%} accept">
                                        4.
                                        {% if past_tense %}
                                            Work Done
                                        {%else%}
                                            Accept Work
                                        {%endif%}
                                    </li>
                                </ol>
                            </div>

app/dashboard/templates/shared/current_balance.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}

          {% if not full %}
            <div id="upper_left" class="d-flex flex-column justify-content-center align-items-center white">
                <div class="d-flex align-items-center">
                    <div style="font-size: 1.5rem" id="sidebar_head" class="pl-4 pr-4 pt-4 pb-2 font-weight-300">
                        <svg width="30px"  height="30px"  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="lds-radio" style="background: none;">
                        <circle cx="28" cy="75" r="11" ng-attr-fill="{{config.c1}}" fill="#fff">
                          <animate attributeName="fill-opacity" calcMode="linear" values="0;1;1" keyTimes="0;0.2;1" dur="1" begin="0s" repeatCount="indefinite"></animate>
                        </circle>
                        <path d="M28 47A28 28 0 0 1 56 75" fill="none" ng-attr-stroke="{{config.c2}}" stroke-width="10" stroke="#ffffff">
                          <animate attributeName="stroke-opacity" calcMode="linear" values="0;1;1" keyTimes="0;0.2;1" dur="1" begin="0.1s" repeatCount="indefinite"></animate>
                        </path>
                        <path d="M28 25A50 50 0 0 1 78 75" fill="none" ng-attr-stroke="{{config.c3}}" stroke-width="10" stroke="#ffffff">
                          <animate attributeName="stroke-opacity" calcMode="linear" values="0;1;1" keyTimes="0;0.2;1" dur="1" begin="0.2s" repeatCount="indefinite"></animate>
                        </path>
                      </svg>
                    </div>
                </div>
                <div class="font-smaller-2 mb-4" style="margin: 0px auto; text-align: center; padding: 5px 10px;" id="sidebar_p"></div>
            </div>
          {% else %}
            <div class="d-flex flex-column justify-content-center align-items-center white alternative-balance" style="background-color: #26cd7f;">
              <div class="d-flex align-items-center">
                <div id="sidebar_head" class="font-weight-300">
                    <svg width="30px"  height="30px"  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="lds-radio" style="background: none;">
                    <circle cx="28" cy="75" r="11" ng-attr-fill="{{config.c1}}" fill="#fff">
                      <animate attributeName="fill-opacity" calcMode="linear" values="0;1;1" keyTimes="0;0.2;1" dur="1" begin="0s" repeatCount="indefinite"></animate>
                    </circle>
                    <path d="M28 47A28 28 0 0 1 56 75" fill="none" ng-attr-stroke="{{config.c2}}" stroke-width="10" stroke="#ffffff">
                      <animate attributeName="stroke-opacity" calcMode="linear" values="0;1;1" keyTimes="0;0.2;1" dur="1" begin="0.1s" repeatCount="indefinite"></animate>
                    </path>
                    <path d="M28 25A50 50 0 0 1 78 75" fill="none" ng-attr-stroke="{{config.c3}}" stroke-width="10" stroke="#ffffff">
                      <animate attributeName="stroke-opacity" calcMode="linear" values="0;1;1" keyTimes="0;0.2;1" dur="1" begin="0.2s" repeatCount="indefinite"></animate>
                    </path>
                  </svg>
                </div>
              </div>
              <div class="font-smaller-2" id="sidebar_p"></div>
            </div>
          {% endif %}

app/dashboard/templates/shared/name.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}
                            <div class="w-100 mt-2">
                                <label for=fullName>Full Name:</label>
                                <input name='fullName' id='fullName'  class="w-100 gc-round-text-input" type="text" placeholder="John Smith (optional)" value="{% if name %}{{name}}{% endif %}" />
                            </div>

app/dashboard/templates/shared/nav_auth.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}
{% load static %}
                {% if github_handle %}
                  <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{github_handle}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if source == 'authed' %}
                          <a class="dropdown-item" href="{% url "tip" %}"><img src="{% static "v2/images/icons/paperplane.png" %}" width=20px height=20px> Send Tip</a>
                          <a class="dropdown-item" href="{% url "new_funding" %}"><img src="{% static "v2/images/icons/accelerator.png" %}" width=20px height=20px> Fund Issue</a>
                      {% else %}
                          <a class="dropdown-item" href="{% url "get_gitcoin" %}"><img src="{% static "v2/images/icons/bolt.png" %}" width=20px height=20px>  Get Started</a>
                      {% endif %}
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url "profile" %}{{github_handle}}"><img src="{% static "v2/images/icons/anchor.png" %}" width=20px height=20px>  View Profile</a>
                      <a class="dropdown-item" href="{% url "email_settings" "" %}"><img src="{% static "v2/images/icons/mail.png" %}" width=20px height=20px>  Email Settings</a>

                      {% if unclaimed_tips %}

                          <div class="dropdown-divider"></div>
                          {% for tip in unclaimed_tips %}
                            <a class="dropdown-item" href="{{tip.url}}"><img src="{% static "v2/images/icons/cards_diamonds.png" %}" width=20px height=20px> Claim ${{tip.value_in_usdt}} Tip</a>
                          {% endfor %}

                      {% endif %}

                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url "github:github_logout" %}?redirect_uri={{ request.get_full_path }}"><img src="{% static "v2/images/icons/lock_open.png" %}" width=20px height=20px>  Log Out</a>
                    </div>
                  </div>
                {% else %}
                <a class="nav-link" href="{% url "github:github_auth" %}?redirect_uri={{ request.get_full_path }}" onclick="dataLayer.push({'event': 'login'});">
                    Login
                </a>
                {% endif %}
                <img class="nav_avatar" src="{% url "avatar" %}?repo=https://github.com/{% if github_handle %}{{github_handle}}{%else%}Self{%endif%}" width=50 height=50 >

app/dashboard/templates/shared/network_status.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core 

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}
                            <div id=network_status class="w-100" style="text-align: center;">
                                <div class="w-40">
                                        Web3: <span>☑ - Enabled</span>
                                        <br>
                                        Eth: <span>☑ - Available</span>
                                </div>
                            </div>

app/dashboard/templates/shared/newsletter.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}
{% load static %}
<link rel="stylesheet" href="{% static "v2/css/newsletter.css" %}">
<div class="row newsletter text-center" >
  <form action="//gitcoin.us16.list-manage.com/subscribe/post?u=f9f93e162a8732673b942cbda&amp;id=791d905ad8"
    method="post" id="mc-embedded-subscribe-form" class="col-12 validate"
    name="mc-embedded-subscribe-form" target="_blank" novalidate>

    <h4 class="col-12" id="title">
      {%if newsletter_headline %}
        {{newsletter_headline}}
      {% else %}
        Join Our Newsletter !
      {% endif %}
    </h4>
    <label for="newsletter-input">(Emails once a week max, & we never sell your data)</label>
    <div class="col-12">
      <input name="EMAIL" placeholder="you@domain.com" id="newsletter-input" required>
      <button id="newsletter-subscribe" type="submit" class="addon subscribe"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
    </div>
  </form>
</div>

app/dashboard/templates/shared/no_metamask_error.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}
{% load static %}
                    <div id="no_metamask_error" class="blocking_error" style="display: none">
                        {% include 'shared/bounty_nav.html' with active_item=1 %}
                        <img src="{% static "v2/images/prime.png" %}">
                        <br>
                        <h3>To continue, enable Web3.</h3>
                        <p>
                            Web3 is the same web you know and love, but with Ethereum-enabled functionality.
                        </p>
                        <p>
                            The fastest and easiest way to add Web3 to your browser is to install <a target="_blank" rel="noopener noreferrer" href="https://metamask.io/?utm_source=gitcoin.co&utm_medium=referral">Metamask</a>. To continue submitting a bounty, please install Metamask and return to this page.
                        </p>
                        <p class="float-right">
                            <a class="btn btn-sm btn-info mt-3 pulseClick" role="button" id="submit" href="https://metamask.io">Install MetaMask</a>
                            <br>
                            - or -
                            <br>
                            <a target="_blank" rel="noopener noreferrer" href="https://github.com/gitcoinco/gitcoinco/issues/4">Can't get web3 to work?  Get help here.</a>
                        </p>
                    </div>

app/dashboard/templates/shared/search_bar.html
{% comment %}
    Copyright (C) 2017 Gitcoin Core 

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

{% endcomment %}

                <div class="search_bar">
                <div class="row mt-4 align-items-center " >
                    <div class="col-1"></div>
                    <div class="col-5">
                        <div class="search-area d-flex justify-content-center">
                            <input class="gc-round-text-input gc-border-black w-100" id="keywords" type="text" placeholder="keyword1, keyword2, keyword3" />
                        </div>
                    </div>
                    <div class="col-1"></div>
                    <div class="col-2">
                        <a class="btn btn-outline-dark pl-4 pr-4" role="button" id="new_search" href="#">Search</a>
                    </div>
                </div>
                <div class="row mt-3 sort_row">
                    <div class="col-1"></div>
                    <div class="col-6 d-flex align-items-center order_by">
                        <div class="ml-3">Sort:</div>
                        <div class="ml-5 font-smaller-2 sort_option selected" data-key='web3_created' data-direction="-">Created</div>
                        <div class="ml-4 font-smaller-2 sort_option" data-key='_val_usd_db' data-direction="-">Value</div>
                        <div class="ml-4 font-smaller-2 sort_option" data-key='idx_experience_level'>Difficulty</div>
                        <div class="ml-4 font-smaller-2 sort_option" data-key='idx_project_length'>Length</div>
                    </div>
                    <div class="col-2">
                        <a class="pl-4 pr-4 font-smaller-2 save_search" href="/save_search" style="color: #000;">Save Search</a>
                    </div>
                </div>
                </div>
                
                